name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Use Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 15.x

      - name: Install and Build
        run: |
          npm install
          npm run build:docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs-dist
